/**
 * Integration test for Phase 13's daily player report pass (§16 of
 * the build plan — generated by the strong model from actual
 * game_events rows only, never fabricated; same once-per-completed-
 * game-day cadence as Phase 11's memory extraction). Runs against a
 * real Postgres; skipped without DATABASE_URL like the rest of this
 * suite.
 *
 * The fabricated day window is pinned to the year 2000 specifically so
 * it can never overlap real dev/test activity from any other
 * character — generateDailyReports sweeps every character in the
 * table (same design as processTick), and a window anywhere near "now"
 * would pull in whatever seeded/dev activity happened to be running
 * alongside this test.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { eq } from 'drizzle-orm';
import { schema } from '@ai-world/database';
import { MockProvider } from '@ai-world/ai';
import { generateDailyReports } from '../daily-report.js';

const DB_URL = process.env.DATABASE_URL;

describe.skipIf(!DB_URL)('generateDailyReports', () => {
  let client: ReturnType<typeof postgres>;
  let db: ReturnType<typeof drizzle<typeof schema>>;
  let characterId: string;
  let cycleId: string;
  // Distinctive and far outside any real game day number this world
  // will ever reach, so it can't collide with actual gameplay data.
  const dayNumber = 987654;

  const dayStart = new Date('2000-01-01T00:00:00Z');
  const dayEnd = new Date('2000-01-02T00:00:00Z');
  const gameDayRealSeconds = 86400;
  // generateDailyReports computes the day's window arithmetically from
  // a world epoch (gameDayRealTimeWindow), not from the game_cycles
  // row — back-solve the epoch so day `dayNumber` lands exactly on
  // [dayStart, dayEnd).
  const cycleStartedAt = new Date(dayStart.getTime() - dayNumber * gameDayRealSeconds * 1000);

  beforeAll(async () => {
    client = postgres(DB_URL!);
    db = drizzle(client, { schema });

    const [character] = await db
      .insert(schema.characters)
      .values({
        name: 'Daily Report Test Character',
        age: 40,
        background: 'A character created to test the daily player report.',
        personalityTraits: [],
        skills: [],
        ambitions: [],
        archetype: 'wealth-seeker',
      })
      .returning({ id: schema.characters.id });
    characterId = character.id;

    const [cycle] = await db
      .insert(schema.gameCycles)
      .values({ dayNumber, startedAt: dayStart, endedAt: dayEnd })
      .returning({ id: schema.gameCycles.id });
    cycleId = cycle.id;

    await db.insert(schema.gameEvents).values([
      {
        type: 'MONEY_EARNED',
        actorCharacterId: characterId,
        payload: { amount_cents: 120 },
        importance: 0.3,
        createdAt: new Date(dayStart.getTime() + 1000),
      },
      {
        type: 'CONVERSATION_STARTED',
        actorCharacterId: characterId,
        payload: { message: 'Well met.' },
        importance: 0.3,
        createdAt: new Date(dayStart.getTime() + 2000),
      },
    ]);
  });

  afterAll(async () => {
    await db.delete(schema.dailyReports).where(eq(schema.dailyReports.characterId, characterId));
    await db.delete(schema.aiUsage).where(eq(schema.aiUsage.characterId, characterId));
    await db.delete(schema.gameEvents).where(eq(schema.gameEvents.actorCharacterId, characterId));
    await db.delete(schema.gameCycles).where(eq(schema.gameCycles.id, cycleId));
    await db.delete(schema.characters).where(eq(schema.characters.id, characterId));
    await client.end();
  });

  it('writes a report and an ai_usage row for a character with events that day', async () => {
    const result = await generateDailyReports(
      db,
      new MockProvider(),
      dayNumber,
      'mock',
      'mock',
      cycleStartedAt,
      gameDayRealSeconds
    );

    expect(result.errors.some((e) => e.includes(characterId))).toBe(false);
    expect(result.charactersProcessed).toBeGreaterThanOrEqual(1);
    expect(result.reportsWritten).toBeGreaterThanOrEqual(1);

    const reportRows = await db
      .select()
      .from(schema.dailyReports)
      .where(eq(schema.dailyReports.characterId, characterId));
    expect(reportRows.length).toBe(1);
    expect(reportRows[0].gameDay).toBe(dayNumber);
    expect(reportRows[0].summary.length).toBeGreaterThan(0);
    expect(reportRows[0].eventCount).toBe(2);

    const usageRows = await db
      .select()
      .from(schema.aiUsage)
      .where(eq(schema.aiUsage.characterId, characterId));
    expect(usageRows.length).toBe(1);
    expect(usageRows[0].purpose).toBe('summarizeEvents');
  });

  it('is idempotent — a second call for the same day does not duplicate the report', async () => {
    const before = await db
      .select()
      .from(schema.dailyReports)
      .where(eq(schema.dailyReports.characterId, characterId));
    expect(before.length).toBe(1);

    const result = await generateDailyReports(
      db,
      new MockProvider(),
      dayNumber,
      'mock',
      'mock',
      cycleStartedAt,
      gameDayRealSeconds
    );
    expect(result.reportsWritten).toBe(0);

    const after = await db
      .select()
      .from(schema.dailyReports)
      .where(eq(schema.dailyReports.characterId, characterId));
    expect(after.length).toBe(1);
    expect(after[0].id).toBe(before[0].id);
  });

  it('returns cleanly with zero writes for a day number with no recorded cycle', async () => {
    const result = await generateDailyReports(
      db,
      new MockProvider(),
      -987654,
      'mock',
      'mock',
      cycleStartedAt,
      gameDayRealSeconds
    );
    expect(result).toEqual({ charactersProcessed: 0, reportsWritten: 0, errors: [] });
  });
});
