import { and, desc, eq, gte, lte } from 'drizzle-orm';
import type { Db } from '@ai-world/database';
import { aiUsage, characters, dailyReports, gameCycles, gameEvents } from '@ai-world/database';
import type { AgentModelProvider } from '@ai-world/ai';
import { gameDayRealTimeWindow, describeGameEvent } from '@ai-world/shared';

// Same token-minimization rationale as memory-extraction.ts's cap —
// a report summarizes the day's most important beats, not a full
// transcript.
const MAX_EVENTS_PER_CHARACTER_PER_DAY = 30;

export interface DailyReportGenerationResult {
  charactersProcessed: number;
  reportsWritten: number;
  errors: string[];
}

/**
 * Generates one daily report per character for a completed game day
 * (§16: "generated by the strong model from actual game_events rows,
 * never fabricated"), same once-per-day cadence and same
 * epoch-derived day window as extractDailyMemories — see that
 * module's doc comment for why the window is computed arithmetically
 * rather than read off a `game_cycles` row.
 *
 * Idempotent: if a report already exists for a character+day (e.g.
 * this ever ran twice for the same day), it's skipped rather than
 * duplicated or overwritten.
 */
export async function generateDailyReports(
  db: Db,
  provider: AgentModelProvider,
  completedDayNumber: number,
  providerName: string,
  modelName: string,
  cycleStartedAt: Date,
  gameDayRealSeconds: number
): Promise<DailyReportGenerationResult> {
  const errors: string[] = [];
  let reportsWritten = 0;
  let charactersProcessed = 0;

  if (completedDayNumber < 0) {
    return { charactersProcessed: 0, reportsWritten: 0, errors };
  }

  const { start: dayStart, end: dayEnd } = gameDayRealTimeWindow(
    completedDayNumber,
    cycleStartedAt,
    gameDayRealSeconds
  );

  const [completedCycle] = await db
    .select()
    .from(gameCycles)
    .where(eq(gameCycles.dayNumber, completedDayNumber))
    .limit(1);

  const allCharacters = await db.select({ id: characters.id }).from(characters);

  for (const char of allCharacters) {
    try {
      const [existingReport] = await db
        .select({ id: dailyReports.id })
        .from(dailyReports)
        .where(and(eq(dailyReports.characterId, char.id), eq(dailyReports.gameDay, completedDayNumber)))
        .limit(1);
      if (existingReport) continue;

      const dayEvents = await db
        .select()
        .from(gameEvents)
        .where(
          and(
            eq(gameEvents.actorCharacterId, char.id),
            gte(gameEvents.createdAt, dayStart),
            lte(gameEvents.createdAt, dayEnd)
          )
        )
        .orderBy(desc(gameEvents.importance))
        .limit(MAX_EVENTS_PER_CHARACTER_PER_DAY);

      // Nothing happened — no report to write, no tokens spent.
      if (dayEvents.length === 0) continue;
      charactersProcessed++;

      const startMs = Date.now();
      const result = await provider.summarizeEvents({
        characterId: char.id,
        events: dayEvents.map((e) => ({
          type: e.type,
          description: describeGameEvent(e),
          createdAt: e.createdAt,
        })),
        gameCycleId: completedCycle?.id ?? '',
      });
      const latencyMs = Date.now() - startMs;

      const usage = provider.getLastCallUsage?.() ?? {
        inputTokens: 0,
        outputTokens: 0,
        cacheReadTokens: 0,
        cacheWriteTokens: 0,
        estimatedCostCents: 0,
      };

      await db.insert(aiUsage).values({
        characterId: char.id,
        gameCycleId: completedCycle?.id ?? null,
        provider: providerName,
        model: modelName,
        purpose: 'summarizeEvents',
        inputTokens: usage.inputTokens,
        outputTokens: usage.outputTokens,
        cacheReadTokens: usage.cacheReadTokens,
        cacheWriteTokens: usage.cacheWriteTokens,
        latencyMs,
        estimatedCostCents: usage.estimatedCostCents,
        success: true,
        createdAt: new Date(),
      });

      await db.insert(dailyReports).values({
        characterId: char.id,
        gameDay: completedDayNumber,
        summary: result.summary,
        eventCount: dayEvents.length,
        createdAt: new Date(),
      });
      reportsWritten++;
    } catch (err) {
      errors.push(`Character ${char.id}: ${String(err)}`);
      // One character's report failing never blocks the rest of the
      // day's reports, same isolation principle as the tick loop.
    }
  }

  return { charactersProcessed, reportsWritten, errors };
}
